services:
  - type: web
    name: my-ts-server
    env: node
    buildCommand: echo "Build skipped - using prebuilt dist"
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
