services:
  - type: web
    name: my-express-app
    env: node
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      echo "Build skipped - using prebuilt dist"
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
