import {
  XMarkIcon,
  PauseIcon,
  PlayIcon,
  CameraIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowUpRightIcon,
  ArrowRightIcon,
  DocumentIcon,
  PhotoIcon,
  SignalSlashIcon,
  PlusIcon,
  EyeIcon,
  EyeSlashIcon,
  PencilIcon,
  MagnifyingGlassIcon,
  UserCircleIcon,
  EnvelopeIcon,
  KeyIcon,
  CheckBadgeIcon,
  LockClosedIcon,
  ChatBubbleLeftRightIcon,
  UserPlusIcon,
  UsersIcon,
  CheckIcon,
  UserIcon,
  ArrowLeftIcon,
  PhoneIcon,
  VideoCameraIcon,
  EllipsisVerticalIcon,
  Cog6ToothIcon,
  ChevronDownIcon,
  ClipboardIcon,
  ArrowUturnLeftIcon,
  InformationCircleIcon,
  MinusCircleIcon,
  NoSymbolIcon,
  BellIcon,
  MusicalNoteIcon,
  ArrowDownTrayIcon,
} from "@heroicons/react/16/solid";
import { LuClock4, LuSend, LuSmile } from "react-icons/lu";
import { RiAttachment2 } from "react-icons/ri";
import { IoMicOutline } from "react-icons/io5";
import { FaPause } from "react-icons/fa6";
import { MdDelete, MdOutlineCameraAlt } from "react-icons/md";
import { IoMic, IoPlay } from "react-icons/io5";
import { LiaUserShieldSolid } from "react-icons/lia";
import { CiLock ,CiBellOn } from "react-icons/ci";
import { GoogleIcon } from "./SvgIcons";
export const Icons = {
  XMarkIcon,
  PauseIcon,
  PlayIcon,
  CameraIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowUpRightIcon,
  ArrowRightIcon,
  DocumentIcon,
  PhotoIcon,
  SignalSlashIcon,
  PlusIcon,
  EyeIcon,
  EyeSlashIcon,
  PencilIcon,
  MagnifyingGlassIcon,
  UserCircleIcon,
  EnvelopeIcon,
  KeyIcon,
  CheckBadgeIcon,
  LockClosedIcon,
  ChatBubbleLeftRightIcon,
  UserPlusIcon,
  UsersIcon,
  CheckIcon,
  UserIcon,
  ArrowLeftIcon,
  PhoneIcon,
  VideoCameraIcon,
  EllipsisVerticalIcon,
  Cog6ToothIcon,
  ChevronDownIcon,
  ClipboardIcon,
  ArrowUturnLeftIcon,
  InformationCircleIcon,
  MinusCircleIcon,
  NoSymbolIcon,
  BellIcon,
  MusicalNoteIcon,
  ArrowDownTrayIcon,
  UserShield: LiaUserShieldSolid,
  ClockIcon: LuClock4,
  SendIcon: LuSend,
  SmileIcon: LuSmile,
  AttachmentIcons: RiAttachment2,
  MicPrimary: IoMicOutline,
  MicSecondary: IoMic,
  PauseSeconday: FaPause,
  DeleteIcon: MdDelete,
  PlaySeconday: IoPlay,
  CameraIconSecondary: MdOutlineCameraAlt,
  GoogleIcon,
  CiLock,
  CiBellOn 
};
